// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: aspect/v2/entry_api.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterTxResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFilter bool `protobuf:"varint,1,opt,name=is_filter,json=isFilter,proto3" json:"is_filter,omitempty"`
}

func (x *FilterTxResult) Reset() {
	*x = FilterTxResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTxResult) ProtoMessage() {}

func (x *FilterTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTxResult.ProtoReflect.Descriptor instead.
func (*FilterTxResult) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{0}
}

func (x *FilterTxResult) GetIsFilter() bool {
	if x != nil {
		return x.IsFilter
	}
	return false
}

type VerifyTxResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsVerified bool `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
}

func (x *VerifyTxResult) Reset() {
	*x = VerifyTxResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTxResult) ProtoMessage() {}

func (x *VerifyTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTxResult.ProtoReflect.Descriptor instead.
func (*VerifyTxResult) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTxResult) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type GetPayMasterResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayMaster string `protobuf:"bytes,1,opt,name=pay_master,json=payMaster,proto3" json:"pay_master,omitempty"`
}

func (x *GetPayMasterResult) Reset() {
	*x = GetPayMasterResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayMasterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayMasterResult) ProtoMessage() {}

func (x *GetPayMasterResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayMasterResult.ProtoReflect.Descriptor instead.
func (*GetPayMasterResult) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetPayMasterResult) GetPayMaster() string {
	if x != nil {
		return x.PayMaster
	}
	return ""
}

type AspectCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AspectId string `protobuf:"bytes,1,opt,name=aspect_id,json=aspectId,proto3" json:"aspect_id,omitempty"`
	Version  uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Priority uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Code     []byte `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AspectCode) Reset() {
	*x = AspectCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspectCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectCode) ProtoMessage() {}

func (x *AspectCode) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectCode.ProtoReflect.Descriptor instead.
func (*AspectCode) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{3}
}

func (x *AspectCode) GetAspectId() string {
	if x != nil {
		return x.AspectId
	}
	return ""
}

func (x *AspectCode) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AspectCode) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AspectCode) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

// EthBlock for querying ethereum block from aspect
type EthBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *EthBlockHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Uncles       []*EthBlockHeader `protobuf:"bytes,2,rep,name=uncles,proto3" json:"uncles,omitempty"`
	Transactions []*EthTransaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Hash         string            `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Size         uint64            `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	DataHash     []byte            `protobuf:"bytes,6,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
}

func (x *EthBlock) Reset() {
	*x = EthBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthBlock) ProtoMessage() {}

func (x *EthBlock) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthBlock.ProtoReflect.Descriptor instead.
func (*EthBlock) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{4}
}

func (x *EthBlock) GetHeader() *EthBlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EthBlock) GetUncles() []*EthBlockHeader {
	if x != nil {
		return x.Uncles
	}
	return nil
}

func (x *EthBlock) GetTransactions() []*EthTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *EthBlock) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EthBlock) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EthBlock) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

type EthStateChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // hex string of account
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EthStateChange) Reset() {
	*x = EthStateChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthStateChange) ProtoMessage() {}

func (x *EthStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthStateChange.ProtoReflect.Descriptor instead.
func (*EthStateChange) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{5}
}

func (x *EthStateChange) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EthStateChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type EthStateChanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All []*EthStateChange `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *EthStateChanges) Reset() {
	*x = EthStateChanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthStateChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthStateChanges) ProtoMessage() {}

func (x *EthStateChanges) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthStateChanges.ProtoReflect.Descriptor instead.
func (*EthStateChanges) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{6}
}

func (x *EthStateChanges) GetAll() []*EthStateChange {
	if x != nil {
		return x.All
	}
	return nil
}

type EthCallStacks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calls map[uint64]*EthStackTransaction `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EthCallStacks) Reset() {
	*x = EthCallStacks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthCallStacks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthCallStacks) ProtoMessage() {}

func (x *EthCallStacks) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthCallStacks.ProtoReflect.Descriptor instead.
func (*EthCallStacks) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{7}
}

func (x *EthCallStacks) GetCalls() map[uint64]*EthStackTransaction {
	if x != nil {
		return x.Calls
	}
	return nil
}

type EthCallStackQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToEq          string   `protobuf:"bytes,1,opt,name=to_eq,json=toEq,proto3" json:"to_eq,omitempty"`
	IndexIn       []uint64 `protobuf:"varint,2,rep,packed,name=index_in,json=indexIn,proto3" json:"index_in,omitempty"`
	ParentIndexEq uint64   `protobuf:"varint,3,opt,name=parentIndex_eq,json=parentIndexEq,proto3" json:"parentIndex_eq,omitempty"`
}

func (x *EthCallStackQuery) Reset() {
	*x = EthCallStackQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_entry_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthCallStackQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthCallStackQuery) ProtoMessage() {}

func (x *EthCallStackQuery) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_entry_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthCallStackQuery.ProtoReflect.Descriptor instead.
func (*EthCallStackQuery) Descriptor() ([]byte, []int) {
	return file_aspect_v2_entry_api_proto_rawDescGZIP(), []int{8}
}

func (x *EthCallStackQuery) GetToEq() string {
	if x != nil {
		return x.ToEq
	}
	return ""
}

func (x *EthCallStackQuery) GetIndexIn() []uint64 {
	if x != nil {
		return x.IndexIn
	}
	return nil
}

func (x *EthCallStackQuery) GetParentIndexEq() uint64 {
	if x != nil {
		return x.ParentIndexEq
	}
	return 0
}

var File_aspect_v2_entry_api_proto protoreflect.FileDescriptor

var file_aspect_v2_entry_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x1a, 0x1c, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x76,
	0x32, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x78,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x78, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x33, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x61, 0x79, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x61, 0x79, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x73, 0x0a, 0x0a, 0x41,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0xf3, 0x01, 0x0a, 0x08, 0x45, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x31, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x31, 0x0a, 0x06, 0x75, 0x6e, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x75, 0x6e, 0x63,
	0x6c, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x22, 0x40, 0x0a, 0x0e, 0x45, 0x74, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x0f, 0x45, 0x74, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x03, 0x61,
	0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x22, 0xa4, 0x01, 0x0a, 0x0d, 0x45, 0x74, 0x68,
	0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x39, 0x0a, 0x05, 0x63, 0x61,
	0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x73, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x63, 0x61, 0x6c, 0x6c, 0x73, 0x1a, 0x58, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32,
	0x2e, 0x45, 0x74, 0x68, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x6a, 0x0a, 0x11, 0x45, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x45, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x5f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x49, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x5f, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x71, 0x42, 0x8e, 0x01, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x42, 0x0d, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x74, 0x65, 0x6c,
	0x61, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x61,
	0x73, 0x64, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa,
	0x02, 0x09, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x56, 0x32, 0xca, 0x02, 0x09, 0x41, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x5c, 0x56, 0x32, 0xe2, 0x02, 0x15, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0a, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x3a, 0x3a, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aspect_v2_entry_api_proto_rawDescOnce sync.Once
	file_aspect_v2_entry_api_proto_rawDescData = file_aspect_v2_entry_api_proto_rawDesc
)

func file_aspect_v2_entry_api_proto_rawDescGZIP() []byte {
	file_aspect_v2_entry_api_proto_rawDescOnce.Do(func() {
		file_aspect_v2_entry_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspect_v2_entry_api_proto_rawDescData)
	})
	return file_aspect_v2_entry_api_proto_rawDescData
}

var file_aspect_v2_entry_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aspect_v2_entry_api_proto_goTypes = []interface{}{
	(*FilterTxResult)(nil),      // 0: aspect.v2.FilterTxResult
	(*VerifyTxResult)(nil),      // 1: aspect.v2.VerifyTxResult
	(*GetPayMasterResult)(nil),  // 2: aspect.v2.GetPayMasterResult
	(*AspectCode)(nil),          // 3: aspect.v2.AspectCode
	(*EthBlock)(nil),            // 4: aspect.v2.EthBlock
	(*EthStateChange)(nil),      // 5: aspect.v2.EthStateChange
	(*EthStateChanges)(nil),     // 6: aspect.v2.EthStateChanges
	(*EthCallStacks)(nil),       // 7: aspect.v2.EthCallStacks
	(*EthCallStackQuery)(nil),   // 8: aspect.v2.EthCallStackQuery
	nil,                         // 9: aspect.v2.EthCallStacks.CallsEntry
	(*EthBlockHeader)(nil),      // 10: aspect.v2.EthBlockHeader
	(*EthTransaction)(nil),      // 11: aspect.v2.EthTransaction
	(*EthStackTransaction)(nil), // 12: aspect.v2.EthStackTransaction
}
var file_aspect_v2_entry_api_proto_depIdxs = []int32{
	10, // 0: aspect.v2.EthBlock.header:type_name -> aspect.v2.EthBlockHeader
	10, // 1: aspect.v2.EthBlock.uncles:type_name -> aspect.v2.EthBlockHeader
	11, // 2: aspect.v2.EthBlock.transactions:type_name -> aspect.v2.EthTransaction
	5,  // 3: aspect.v2.EthStateChanges.all:type_name -> aspect.v2.EthStateChange
	9,  // 4: aspect.v2.EthCallStacks.calls:type_name -> aspect.v2.EthCallStacks.CallsEntry
	12, // 5: aspect.v2.EthCallStacks.CallsEntry.value:type_name -> aspect.v2.EthStackTransaction
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_aspect_v2_entry_api_proto_init() }
func file_aspect_v2_entry_api_proto_init() {
	if File_aspect_v2_entry_api_proto != nil {
		return
	}
	file_aspect_v2_base_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aspect_v2_entry_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterTxResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTxResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayMasterResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspectCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthStateChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthStateChanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthCallStacks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_entry_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthCallStackQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspect_v2_entry_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aspect_v2_entry_api_proto_goTypes,
		DependencyIndexes: file_aspect_v2_entry_api_proto_depIdxs,
		MessageInfos:      file_aspect_v2_entry_api_proto_msgTypes,
	}.Build()
	File_aspect_v2_entry_api_proto = out.File
	file_aspect_v2_entry_api_proto_rawDesc = nil
	file_aspect_v2_entry_api_proto_goTypes = nil
	file_aspect_v2_entry_api_proto_depIdxs = nil
}
