// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: aspect/v2/host_api.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// evm api types
type StaticCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From []byte  `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To   []byte  `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
	Data []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	Gas  *uint64 `protobuf:"varint,4,opt,name=gas" json:"gas,omitempty"`
}

func (x *StaticCallRequest) Reset() {
	*x = StaticCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticCallRequest) ProtoMessage() {}

func (x *StaticCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticCallRequest.ProtoReflect.Descriptor instead.
func (*StaticCallRequest) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{0}
}

func (x *StaticCallRequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *StaticCallRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *StaticCallRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StaticCallRequest) GetGas() uint64 {
	if x != nil && x.Gas != nil {
		return *x.Gas
	}
	return 0
}

type StaticCallResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret     []byte  `protobuf:"bytes,1,opt,name=ret" json:"ret,omitempty"`
	VmError *string `protobuf:"bytes,2,opt,name=vm_error,json=vmError" json:"vm_error,omitempty"`
	GasLeft *uint64 `protobuf:"varint,3,req,name=gas_left,json=gasLeft" json:"gas_left,omitempty"`
}

func (x *StaticCallResult) Reset() {
	*x = StaticCallResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticCallResult) ProtoMessage() {}

func (x *StaticCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticCallResult.ProtoReflect.Descriptor instead.
func (*StaticCallResult) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{1}
}

func (x *StaticCallResult) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *StaticCallResult) GetVmError() string {
	if x != nil && x.VmError != nil {
		return *x.VmError
	}
	return ""
}

func (x *StaticCallResult) GetGasLeft() uint64 {
	if x != nil && x.GasLeft != nil {
		return *x.GasLeft
	}
	return 0
}

type JitInherentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender               []byte  `protobuf:"bytes,1,req,name=sender" json:"sender,omitempty"`
	Nonce                *uint64 `protobuf:"varint,2,opt,name=nonce" json:"nonce,omitempty"`
	NonceKey             []byte  `protobuf:"bytes,3,opt,name=nonce_key,json=nonceKey" json:"nonce_key,omitempty"`
	InitCode             []byte  `protobuf:"bytes,4,opt,name=init_code,json=initCode" json:"init_code,omitempty"`
	CallData             []byte  `protobuf:"bytes,5,req,name=call_data,json=callData" json:"call_data,omitempty"`
	CallGasLimit         *uint64 `protobuf:"varint,6,opt,name=call_gas_limit,json=callGasLimit" json:"call_gas_limit,omitempty"`
	VerificationGasLimit *uint64 `protobuf:"varint,7,opt,name=verification_gas_limit,json=verificationGasLimit" json:"verification_gas_limit,omitempty"`
	PaymasterAndData     []byte  `protobuf:"bytes,8,opt,name=paymaster_and_data,json=paymasterAndData" json:"paymaster_and_data,omitempty"`
}

func (x *JitInherentRequest) Reset() {
	*x = JitInherentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JitInherentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitInherentRequest) ProtoMessage() {}

func (x *JitInherentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitInherentRequest.ProtoReflect.Descriptor instead.
func (*JitInherentRequest) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{2}
}

func (x *JitInherentRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *JitInherentRequest) GetNonce() uint64 {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return 0
}

func (x *JitInherentRequest) GetNonceKey() []byte {
	if x != nil {
		return x.NonceKey
	}
	return nil
}

func (x *JitInherentRequest) GetInitCode() []byte {
	if x != nil {
		return x.InitCode
	}
	return nil
}

func (x *JitInherentRequest) GetCallData() []byte {
	if x != nil {
		return x.CallData
	}
	return nil
}

func (x *JitInherentRequest) GetCallGasLimit() uint64 {
	if x != nil && x.CallGasLimit != nil {
		return *x.CallGasLimit
	}
	return 0
}

func (x *JitInherentRequest) GetVerificationGasLimit() uint64 {
	if x != nil && x.VerificationGasLimit != nil {
		return *x.VerificationGasLimit
	}
	return 0
}

func (x *JitInherentRequest) GetPaymasterAndData() []byte {
	if x != nil {
		return x.PaymasterAndData
	}
	return nil
}

type JitInherentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JitInherentHashes [][]byte `protobuf:"bytes,1,rep,name=jit_inherent_hashes,json=jitInherentHashes" json:"jit_inherent_hashes,omitempty"`
	TxHash            []byte   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	Success           *bool    `protobuf:"varint,3,req,name=success" json:"success,omitempty"`
	Ret               []byte   `protobuf:"bytes,4,opt,name=ret" json:"ret,omitempty"`
	ErrorMsg          *string  `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
}

func (x *JitInherentResponse) Reset() {
	*x = JitInherentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JitInherentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitInherentResponse) ProtoMessage() {}

func (x *JitInherentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitInherentResponse.ProtoReflect.Descriptor instead.
func (*JitInherentResponse) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{3}
}

func (x *JitInherentResponse) GetJitInherentHashes() [][]byte {
	if x != nil {
		return x.JitInherentHashes
	}
	return nil
}

func (x *JitInherentResponse) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *JitInherentResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *JitInherentResponse) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *JitInherentResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

// runtime context types
type EthLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*EthLog `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
}

func (x *EthLogs) Reset() {
	*x = EthLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthLogs) ProtoMessage() {}

func (x *EthLogs) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthLogs.ProtoReflect.Descriptor instead.
func (*EthLogs) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{4}
}

func (x *EthLogs) GetLogs() []*EthLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type EthLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address of the contract that generated the event
	Address []byte `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	// topics is a list of topics provided by the contract.
	Topics [][]byte `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
	// data which is supplied by the contract, usually ABI-encoded
	Data  []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	Index *uint64 `protobuf:"varint,4,req,name=index" json:"index,omitempty"`
}

func (x *EthLog) Reset() {
	*x = EthLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthLog) ProtoMessage() {}

func (x *EthLog) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthLog.ProtoReflect.Descriptor instead.
func (*EthLog) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{5}
}

func (x *EthLog) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *EthLog) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *EthLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EthLog) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type EthReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status            *uint64   `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	CumulativeGasUsed *uint64   `protobuf:"varint,2,req,name=cumulative_gas_used,json=cumulativeGasUsed" json:"cumulative_gas_used,omitempty"`
	LogsBloom         []byte    `protobuf:"bytes,3,req,name=logs_bloom,json=logsBloom" json:"logs_bloom,omitempty"`
	EffectiveGasPrice []byte    `protobuf:"bytes,4,req,name=effective_gas_price,json=effectiveGasPrice" json:"effective_gas_price,omitempty"`
	Logs              []*EthLog `protobuf:"bytes,5,rep,name=logs" json:"logs,omitempty"`
}

func (x *EthReceipt) Reset() {
	*x = EthReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthReceipt) ProtoMessage() {}

func (x *EthReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthReceipt.ProtoReflect.Descriptor instead.
func (*EthReceipt) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{6}
}

func (x *EthReceipt) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *EthReceipt) GetCumulativeGasUsed() uint64 {
	if x != nil && x.CumulativeGasUsed != nil {
		return *x.CumulativeGasUsed
	}
	return 0
}

func (x *EthReceipt) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *EthReceipt) GetEffectiveGasPrice() []byte {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return nil
}

func (x *EthReceipt) GetLogs() []*EthLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type EthAccessList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessList []*EthAccessTuple `protobuf:"bytes,1,rep,name=access_list,json=accessList" json:"access_list,omitempty"`
}

func (x *EthAccessList) Reset() {
	*x = EthAccessList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthAccessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthAccessList) ProtoMessage() {}

func (x *EthAccessList) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthAccessList.ProtoReflect.Descriptor instead.
func (*EthAccessList) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{7}
}

func (x *EthAccessList) GetAccessList() []*EthAccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

type EthAccessTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     []byte   `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	StorageKeys [][]byte `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys" json:"storage_keys,omitempty"`
}

func (x *EthAccessTuple) Reset() {
	*x = EthAccessTuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthAccessTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthAccessTuple) ProtoMessage() {}

func (x *EthAccessTuple) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthAccessTuple.ProtoReflect.Descriptor instead.
func (*EthAccessTuple) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{8}
}

func (x *EthAccessTuple) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *EthAccessTuple) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

// trace api types
type StateChangeQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account      []byte   `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	StateVarName *string  `protobuf:"bytes,2,req,name=state_var_name,json=stateVarName" json:"state_var_name,omitempty"`
	Indices      [][]byte `protobuf:"bytes,3,rep,name=indices" json:"indices,omitempty"`
}

func (x *StateChangeQuery) Reset() {
	*x = StateChangeQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChangeQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeQuery) ProtoMessage() {}

func (x *StateChangeQuery) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeQuery.ProtoReflect.Descriptor instead.
func (*StateChangeQuery) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{9}
}

func (x *StateChangeQuery) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *StateChangeQuery) GetStateVarName() string {
	if x != nil && x.StateVarName != nil {
		return *x.StateVarName
	}
	return ""
}

func (x *StateChangeQuery) GetIndices() [][]byte {
	if x != nil {
		return x.Indices
	}
	return nil
}

type CallTreeQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallIdx *int64 `protobuf:"varint,1,req,name=call_idx,json=callIdx" json:"call_idx,omitempty"`
}

func (x *CallTreeQuery) Reset() {
	*x = CallTreeQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallTreeQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTreeQuery) ProtoMessage() {}

func (x *CallTreeQuery) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTreeQuery.ProtoReflect.Descriptor instead.
func (*CallTreeQuery) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{10}
}

func (x *CallTreeQuery) GetCallIdx() int64 {
	if x != nil && x.CallIdx != nil {
		return *x.CallIdx
	}
	return 0
}

type EthCallMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From []byte `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To   []byte `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	// data is the data payload bytes of the transaction.
	Data            []byte   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Gas             *uint64  `protobuf:"varint,4,req,name=gas" json:"gas,omitempty"`
	Value           []byte   `protobuf:"bytes,5,req,name=value" json:"value,omitempty"`
	Ret             []byte   `protobuf:"bytes,6,opt,name=ret" json:"ret,omitempty"`
	GasUsed         *uint64  `protobuf:"varint,7,opt,name=gas_used,json=gasUsed" json:"gas_used,omitempty"`
	Error           *string  `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
	Index           *uint64  `protobuf:"varint,9,req,name=index" json:"index,omitempty"`
	ParentIndex     *int64   `protobuf:"varint,10,opt,name=parent_index,json=parentIndex" json:"parent_index,omitempty"`
	ChildrenIndices []uint64 `protobuf:"varint,11,rep,name=children_indices,json=childrenIndices" json:"children_indices,omitempty"`
}

func (x *EthCallMessage) Reset() {
	*x = EthCallMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthCallMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthCallMessage) ProtoMessage() {}

func (x *EthCallMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthCallMessage.ProtoReflect.Descriptor instead.
func (*EthCallMessage) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{11}
}

func (x *EthCallMessage) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EthCallMessage) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EthCallMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EthCallMessage) GetGas() uint64 {
	if x != nil && x.Gas != nil {
		return *x.Gas
	}
	return 0
}

func (x *EthCallMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EthCallMessage) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *EthCallMessage) GetGasUsed() uint64 {
	if x != nil && x.GasUsed != nil {
		return *x.GasUsed
	}
	return 0
}

func (x *EthCallMessage) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *EthCallMessage) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *EthCallMessage) GetParentIndex() int64 {
	if x != nil && x.ParentIndex != nil {
		return *x.ParentIndex
	}
	return 0
}

func (x *EthCallMessage) GetChildrenIndices() []uint64 {
	if x != nil {
		return x.ChildrenIndices
	}
	return nil
}

type EthStateChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   []byte  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Value     []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	CallIndex *uint64 `protobuf:"varint,3,req,name=call_index,json=callIndex" json:"call_index,omitempty"`
}

func (x *EthStateChange) Reset() {
	*x = EthStateChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthStateChange) ProtoMessage() {}

func (x *EthStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthStateChange.ProtoReflect.Descriptor instead.
func (*EthStateChange) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{12}
}

func (x *EthStateChange) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *EthStateChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EthStateChange) GetCallIndex() uint64 {
	if x != nil && x.CallIndex != nil {
		return *x.CallIndex
	}
	return 0
}

type EthStateChangeIndices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indices [][]byte `protobuf:"bytes,1,rep,name=indices" json:"indices,omitempty"`
}

func (x *EthStateChangeIndices) Reset() {
	*x = EthStateChangeIndices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthStateChangeIndices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthStateChangeIndices) ProtoMessage() {}

func (x *EthStateChangeIndices) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthStateChangeIndices.ProtoReflect.Descriptor instead.
func (*EthStateChangeIndices) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{13}
}

func (x *EthStateChangeIndices) GetIndices() [][]byte {
	if x != nil {
		return x.Indices
	}
	return nil
}

type EthStateChanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All []*EthStateChange `protobuf:"bytes,1,rep,name=all" json:"all,omitempty"`
}

func (x *EthStateChanges) Reset() {
	*x = EthStateChanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthStateChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthStateChanges) ProtoMessage() {}

func (x *EthStateChanges) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthStateChanges.ProtoReflect.Descriptor instead.
func (*EthStateChanges) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{14}
}

func (x *EthStateChanges) GetAll() []*EthStateChange {
	if x != nil {
		return x.All
	}
	return nil
}

type EthCallTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calls map[uint64]*EthCallMessage `protobuf:"bytes,1,rep,name=calls" json:"calls,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *EthCallTree) Reset() {
	*x = EthCallTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthCallTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthCallTree) ProtoMessage() {}

func (x *EthCallTree) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthCallTree.ProtoReflect.Descriptor instead.
func (*EthCallTree) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{15}
}

func (x *EthCallTree) GetCalls() map[uint64]*EthCallMessage {
	if x != nil {
		return x.Calls
	}
	return nil
}

// basic types
type StringData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *string `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
}

func (x *StringData) Reset() {
	*x = StringData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringData) ProtoMessage() {}

func (x *StringData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringData.ProtoReflect.Descriptor instead.
func (*StringData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{16}
}

func (x *StringData) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type StringArrayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []string `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (x *StringArrayData) Reset() {
	*x = StringArrayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringArrayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArrayData) ProtoMessage() {}

func (x *StringArrayData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArrayData.ProtoReflect.Descriptor instead.
func (*StringArrayData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{17}
}

func (x *StringArrayData) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type UintData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *uint64 `protobuf:"varint,1,req,name=data" json:"data,omitempty"`
}

func (x *UintData) Reset() {
	*x = UintData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UintData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UintData) ProtoMessage() {}

func (x *UintData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UintData.ProtoReflect.Descriptor instead.
func (*UintData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{18}
}

func (x *UintData) GetData() uint64 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

type IntData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *int64 `protobuf:"varint,1,req,name=data" json:"data,omitempty"`
}

func (x *IntData) Reset() {
	*x = IntData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntData) ProtoMessage() {}

func (x *IntData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntData.ProtoReflect.Descriptor instead.
func (*IntData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{19}
}

func (x *IntData) GetData() int64 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

type IntArrayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int64 `protobuf:"varint,1,rep,name=data" json:"data,omitempty"`
}

func (x *IntArrayData) Reset() {
	*x = IntArrayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntArrayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntArrayData) ProtoMessage() {}

func (x *IntArrayData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntArrayData.ProtoReflect.Descriptor instead.
func (*IntArrayData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{20}
}

func (x *IntArrayData) GetData() []int64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type BoolData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *bool `protobuf:"varint,1,req,name=data" json:"data,omitempty"`
}

func (x *BoolData) Reset() {
	*x = BoolData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolData) ProtoMessage() {}

func (x *BoolData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolData.ProtoReflect.Descriptor instead.
func (*BoolData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{21}
}

func (x *BoolData) GetData() bool {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return false
}

type BytesArrayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data [][]byte `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (x *BytesArrayData) Reset() {
	*x = BytesArrayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesArrayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesArrayData) ProtoMessage() {}

func (x *BytesArrayData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesArrayData.ProtoReflect.Descriptor instead.
func (*BytesArrayData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{22}
}

func (x *BytesArrayData) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BytesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
}

func (x *BytesData) Reset() {
	*x = BytesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesData) ProtoMessage() {}

func (x *BytesData) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesData.ProtoReflect.Descriptor instead.
func (*BytesData) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{23}
}

func (x *BytesData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type G1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X []byte `protobuf:"bytes,1,req,name=x" json:"x,omitempty"`
	Y []byte `protobuf:"bytes,2,req,name=y" json:"y,omitempty"`
}

func (x *G1) Reset() {
	*x = G1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G1) ProtoMessage() {}

func (x *G1) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G1.ProtoReflect.Descriptor instead.
func (*G1) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{24}
}

func (x *G1) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *G1) GetY() []byte {
	if x != nil {
		return x.Y
	}
	return nil
}

type G2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X1 []byte `protobuf:"bytes,1,req,name=x1" json:"x1,omitempty"`
	X2 []byte `protobuf:"bytes,2,req,name=x2" json:"x2,omitempty"`
	Y1 []byte `protobuf:"bytes,3,req,name=y1" json:"y1,omitempty"`
	Y2 []byte `protobuf:"bytes,4,req,name=y2" json:"y2,omitempty"`
}

func (x *G2) Reset() {
	*x = G2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2) ProtoMessage() {}

func (x *G2) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2.ProtoReflect.Descriptor instead.
func (*G2) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{25}
}

func (x *G2) GetX1() []byte {
	if x != nil {
		return x.X1
	}
	return nil
}

func (x *G2) GetX2() []byte {
	if x != nil {
		return x.X2
	}
	return nil
}

func (x *G2) GetY1() []byte {
	if x != nil {
		return x.Y1
	}
	return nil
}

func (x *G2) GetY2() []byte {
	if x != nil {
		return x.Y2
	}
	return nil
}

type Bn256AddInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *G1 `protobuf:"bytes,1,req,name=a" json:"a,omitempty"`
	B *G1 `protobuf:"bytes,2,req,name=b" json:"b,omitempty"`
}

func (x *Bn256AddInput) Reset() {
	*x = Bn256AddInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bn256AddInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bn256AddInput) ProtoMessage() {}

func (x *Bn256AddInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bn256AddInput.ProtoReflect.Descriptor instead.
func (*Bn256AddInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{26}
}

func (x *Bn256AddInput) GetA() *G1 {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *Bn256AddInput) GetB() *G1 {
	if x != nil {
		return x.B
	}
	return nil
}

type Bn256ScalarMulInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A      *G1    `protobuf:"bytes,1,req,name=a" json:"a,omitempty"`
	Scalar []byte `protobuf:"bytes,2,req,name=scalar" json:"scalar,omitempty"`
}

func (x *Bn256ScalarMulInput) Reset() {
	*x = Bn256ScalarMulInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bn256ScalarMulInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bn256ScalarMulInput) ProtoMessage() {}

func (x *Bn256ScalarMulInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bn256ScalarMulInput.ProtoReflect.Descriptor instead.
func (*Bn256ScalarMulInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{27}
}

func (x *Bn256ScalarMulInput) GetA() *G1 {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *Bn256ScalarMulInput) GetScalar() []byte {
	if x != nil {
		return x.Scalar
	}
	return nil
}

type Bn256PairingInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cs []*G1 `protobuf:"bytes,1,rep,name=cs" json:"cs,omitempty"`
	Ts []*G2 `protobuf:"bytes,2,rep,name=ts" json:"ts,omitempty"`
}

func (x *Bn256PairingInput) Reset() {
	*x = Bn256PairingInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_host_api_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bn256PairingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bn256PairingInput) ProtoMessage() {}

func (x *Bn256PairingInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_host_api_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bn256PairingInput.ProtoReflect.Descriptor instead.
func (*Bn256PairingInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_host_api_proto_rawDescGZIP(), []int{28}
}

func (x *Bn256PairingInput) GetCs() []*G1 {
	if x != nil {
		return x.Cs
	}
	return nil
}

func (x *Bn256PairingInput) GetTs() []*G2 {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_aspect_v2_host_api_proto protoreflect.FileDescriptor

var file_aspect_v2_host_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x32, 0x22, 0x5d, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x67, 0x61, 0x73, 0x22, 0x5a, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6d,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x6d,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x5f, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x07, 0x67, 0x61, 0x73, 0x4c, 0x65, 0x66, 0x74,
	0x22, 0xa3, 0x02, 0x0a, 0x12, 0x4a, 0x69, 0x74, 0x49, 0x6e, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x02,
	0x28, 0x0c, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0e,
	0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x67, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x47, 0x61, 0x73, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x34, 0x0a, 0x16, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x67, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x14, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x61, 0x79, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x70, 0x61, 0x79, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa7, 0x01, 0x0a, 0x13, 0x4a, 0x69, 0x74, 0x49, 0x6e,
	0x68, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x6a, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x11, 0x6a, 0x69, 0x74,
	0x49, 0x6e, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x30, 0x0a, 0x07, 0x45, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x6c,
	0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f,
	0x67, 0x73, 0x22, 0x64, 0x0a, 0x06, 0x45, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xca, 0x01, 0x0a, 0x0a, 0x45, 0x74, 0x68,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x2e, 0x0a, 0x13, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x67, 0x61,
	0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x11, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x62, 0x6c, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x12, 0x2e,
	0x0a, 0x13, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x67, 0x61, 0x73, 0x5f,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x11, 0x65, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x52,
	0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x4b, 0x0a, 0x0d, 0x45, 0x74, 0x68, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x4d, 0x0a, 0x0e, 0x45, 0x74, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x75, 0x70, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79,
	0x73, 0x22, 0x6c, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x24, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x56, 0x61,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x2a, 0x0a, 0x0d, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x72, 0x65, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x78, 0x22, 0x97, 0x02, 0x0a, 0x0e,
	0x45, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x04, 0x52, 0x03, 0x67, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x67, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x09, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x0f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x49, 0x6e,
	0x64, 0x69, 0x63, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x0e, 0x45, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x63, 0x61, 0x6c,
	0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x31, 0x0a, 0x15, 0x45, 0x74, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x45, 0x74, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x03,
	0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x22, 0x9b, 0x01, 0x0a, 0x0b, 0x45, 0x74,
	0x68, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x72, 0x65, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x63, 0x61, 0x6c,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x72, 0x65, 0x65,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x63, 0x61, 0x6c,
	0x6c, 0x73, 0x1a, 0x53, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x74,
	0x68, 0x43, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x1e, 0x0a, 0x08, 0x55, 0x69, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x1d, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x0e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x02, 0x47, 0x31,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x01, 0x79, 0x22, 0x44, 0x0a, 0x02,
	0x47, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x31, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02,
	0x78, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x32, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02,
	0x78, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x31, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02,
	0x79, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x32, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02,
	0x79, 0x32, 0x22, 0x49, 0x0a, 0x0d, 0x42, 0x6e, 0x32, 0x35, 0x36, 0x41, 0x64, 0x64, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x31, 0x52, 0x01, 0x61,
	0x12, 0x1b, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x31, 0x52, 0x01, 0x62, 0x22, 0x4a, 0x0a,
	0x13, 0x42, 0x6e, 0x32, 0x35, 0x36, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x4d, 0x75, 0x6c, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x31, 0x52, 0x01,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x22, 0x51, 0x0a, 0x11, 0x42, 0x6e, 0x32,
	0x35, 0x36, 0x50, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1d,
	0x0a, 0x02, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x31, 0x52, 0x02, 0x63, 0x73, 0x12, 0x1d, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x32, 0x52, 0x02, 0x74, 0x73, 0x42, 0x8f, 0x01, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x42, 0x0c,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x74, 0x65, 0x6c,
	0x61, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x41, 0x58,
	0x58, 0xaa, 0x02, 0x09, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x56, 0x32, 0xca, 0x02, 0x09,
	0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5c, 0x56, 0x32, 0xe2, 0x02, 0x15, 0x41, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0a, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x3a, 0x3a, 0x56, 0x32,
}

var (
	file_aspect_v2_host_api_proto_rawDescOnce sync.Once
	file_aspect_v2_host_api_proto_rawDescData = file_aspect_v2_host_api_proto_rawDesc
)

func file_aspect_v2_host_api_proto_rawDescGZIP() []byte {
	file_aspect_v2_host_api_proto_rawDescOnce.Do(func() {
		file_aspect_v2_host_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspect_v2_host_api_proto_rawDescData)
	})
	return file_aspect_v2_host_api_proto_rawDescData
}

var file_aspect_v2_host_api_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_aspect_v2_host_api_proto_goTypes = []any{
	(*StaticCallRequest)(nil),     // 0: aspect.v2.StaticCallRequest
	(*StaticCallResult)(nil),      // 1: aspect.v2.StaticCallResult
	(*JitInherentRequest)(nil),    // 2: aspect.v2.JitInherentRequest
	(*JitInherentResponse)(nil),   // 3: aspect.v2.JitInherentResponse
	(*EthLogs)(nil),               // 4: aspect.v2.EthLogs
	(*EthLog)(nil),                // 5: aspect.v2.EthLog
	(*EthReceipt)(nil),            // 6: aspect.v2.EthReceipt
	(*EthAccessList)(nil),         // 7: aspect.v2.EthAccessList
	(*EthAccessTuple)(nil),        // 8: aspect.v2.EthAccessTuple
	(*StateChangeQuery)(nil),      // 9: aspect.v2.StateChangeQuery
	(*CallTreeQuery)(nil),         // 10: aspect.v2.CallTreeQuery
	(*EthCallMessage)(nil),        // 11: aspect.v2.EthCallMessage
	(*EthStateChange)(nil),        // 12: aspect.v2.EthStateChange
	(*EthStateChangeIndices)(nil), // 13: aspect.v2.EthStateChangeIndices
	(*EthStateChanges)(nil),       // 14: aspect.v2.EthStateChanges
	(*EthCallTree)(nil),           // 15: aspect.v2.EthCallTree
	(*StringData)(nil),            // 16: aspect.v2.StringData
	(*StringArrayData)(nil),       // 17: aspect.v2.StringArrayData
	(*UintData)(nil),              // 18: aspect.v2.UintData
	(*IntData)(nil),               // 19: aspect.v2.IntData
	(*IntArrayData)(nil),          // 20: aspect.v2.IntArrayData
	(*BoolData)(nil),              // 21: aspect.v2.BoolData
	(*BytesArrayData)(nil),        // 22: aspect.v2.BytesArrayData
	(*BytesData)(nil),             // 23: aspect.v2.BytesData
	(*G1)(nil),                    // 24: aspect.v2.G1
	(*G2)(nil),                    // 25: aspect.v2.G2
	(*Bn256AddInput)(nil),         // 26: aspect.v2.Bn256AddInput
	(*Bn256ScalarMulInput)(nil),   // 27: aspect.v2.Bn256ScalarMulInput
	(*Bn256PairingInput)(nil),     // 28: aspect.v2.Bn256PairingInput
	nil,                           // 29: aspect.v2.EthCallTree.CallsEntry
}
var file_aspect_v2_host_api_proto_depIdxs = []int32{
	5,  // 0: aspect.v2.EthLogs.logs:type_name -> aspect.v2.EthLog
	5,  // 1: aspect.v2.EthReceipt.logs:type_name -> aspect.v2.EthLog
	8,  // 2: aspect.v2.EthAccessList.access_list:type_name -> aspect.v2.EthAccessTuple
	12, // 3: aspect.v2.EthStateChanges.all:type_name -> aspect.v2.EthStateChange
	29, // 4: aspect.v2.EthCallTree.calls:type_name -> aspect.v2.EthCallTree.CallsEntry
	24, // 5: aspect.v2.Bn256AddInput.a:type_name -> aspect.v2.G1
	24, // 6: aspect.v2.Bn256AddInput.b:type_name -> aspect.v2.G1
	24, // 7: aspect.v2.Bn256ScalarMulInput.a:type_name -> aspect.v2.G1
	24, // 8: aspect.v2.Bn256PairingInput.cs:type_name -> aspect.v2.G1
	25, // 9: aspect.v2.Bn256PairingInput.ts:type_name -> aspect.v2.G2
	11, // 10: aspect.v2.EthCallTree.CallsEntry.value:type_name -> aspect.v2.EthCallMessage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_aspect_v2_host_api_proto_init() }
func file_aspect_v2_host_api_proto_init() {
	if File_aspect_v2_host_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aspect_v2_host_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StaticCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StaticCallResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JitInherentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*JitInherentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EthLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EthLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EthReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EthAccessList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*EthAccessTuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*StateChangeQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CallTreeQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*EthCallMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*EthStateChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*EthStateChangeIndices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*EthStateChanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*EthCallTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*StringData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*StringArrayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UintData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*IntData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*IntArrayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*BoolData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*BytesArrayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*BytesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*G1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*G2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*Bn256AddInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*Bn256ScalarMulInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_host_api_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*Bn256PairingInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspect_v2_host_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aspect_v2_host_api_proto_goTypes,
		DependencyIndexes: file_aspect_v2_host_api_proto_depIdxs,
		MessageInfos:      file_aspect_v2_host_api_proto_msgTypes,
	}.Build()
	File_aspect_v2_host_api_proto = out.File
	file_aspect_v2_host_api_proto_rawDesc = nil
	file_aspect_v2_host_api_proto_goTypes = nil
	file_aspect_v2_host_api_proto_depIdxs = nil
}
