// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: aspect/v1/hostapi_message.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueKind int32

const (
	ValueKind_INT16   ValueKind = 0
	ValueKind_INT32   ValueKind = 1
	ValueKind_INT64   ValueKind = 2
	ValueKind_INT256  ValueKind = 3
	ValueKind_UINT16  ValueKind = 4
	ValueKind_UINT32  ValueKind = 5
	ValueKind_UINT64  ValueKind = 6
	ValueKind_UINT256 ValueKind = 7
	ValueKind_BOOL    ValueKind = 8
	ValueKind_STRING  ValueKind = 9
)

// Enum value maps for ValueKind.
var (
	ValueKind_name = map[int32]string{
		0: "INT16",
		1: "INT32",
		2: "INT64",
		3: "INT256",
		4: "UINT16",
		5: "UINT32",
		6: "UINT64",
		7: "UINT256",
		8: "BOOL",
		9: "STRING",
	}
	ValueKind_value = map[string]int32{
		"INT16":   0,
		"INT32":   1,
		"INT64":   2,
		"INT256":  3,
		"UINT16":  4,
		"UINT32":  5,
		"UINT64":  6,
		"UINT256": 7,
		"BOOL":    8,
		"STRING":  9,
	}
)

func (x ValueKind) Enum() *ValueKind {
	p := new(ValueKind)
	*p = x
	return p
}

func (x ValueKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueKind) Descriptor() protoreflect.EnumDescriptor {
	return file_aspect_v1_hostapi_message_proto_enumTypes[0].Descriptor()
}

func (ValueKind) Type() protoreflect.EnumType {
	return &file_aspect_v1_hostapi_message_proto_enumTypes[0]
}

func (x ValueKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueKind.Descriptor instead.
func (ValueKind) EnumDescriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{0}
}

type AspectInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeight int64             `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	Tx          *AspTransaction   `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	CurrInnerTx *InnerTransaction `protobuf:"bytes,3,opt,name=currInnerTx,proto3" json:"currInnerTx,omitempty"`
}

func (x *AspectInput) Reset() {
	*x = AspectInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspectInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectInput) ProtoMessage() {}

func (x *AspectInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectInput.ProtoReflect.Descriptor instead.
func (*AspectInput) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{0}
}

func (x *AspectInput) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *AspectInput) GetTx() *AspTransaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *AspectInput) GetCurrInnerTx() *InnerTransaction {
	if x != nil {
		return x.CurrInnerTx
	}
	return nil
}

type AspectOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResultData *anypb.Any `protobuf:"bytes,3,opt,name=resultData,proto3,oneof" json:"resultData,omitempty"`
}

func (x *AspectOutput) Reset() {
	*x = AspectOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspectOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectOutput) ProtoMessage() {}

func (x *AspectOutput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectOutput.ProtoReflect.Descriptor instead.
func (*AspectOutput) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{1}
}

func (x *AspectOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AspectOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AspectOutput) GetResultData() *anypb.Any {
	if x != nil {
		return x.ResultData
	}
	return nil
}

type FilterTxResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFilter bool `protobuf:"varint,1,opt,name=isFilter,proto3" json:"isFilter,omitempty"`
}

func (x *FilterTxResult) Reset() {
	*x = FilterTxResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTxResult) ProtoMessage() {}

func (x *FilterTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTxResult.ProtoReflect.Descriptor instead.
func (*FilterTxResult) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{2}
}

func (x *FilterTxResult) GetIsFilter() bool {
	if x != nil {
		return x.IsFilter
	}
	return false
}

type VerifyTxResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsVerified bool `protobuf:"varint,1,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
}

func (x *VerifyTxResult) Reset() {
	*x = VerifyTxResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTxResult) ProtoMessage() {}

func (x *VerifyTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTxResult.ProtoReflect.Descriptor instead.
func (*VerifyTxResult) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyTxResult) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type GetPayMasterResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayMaster string `protobuf:"bytes,1,opt,name=payMaster,proto3" json:"payMaster,omitempty"`
}

func (x *GetPayMasterResult) Reset() {
	*x = GetPayMasterResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayMasterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayMasterResult) ProtoMessage() {}

func (x *GetPayMasterResult) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayMasterResult.ProtoReflect.Descriptor instead.
func (*GetPayMasterResult) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetPayMasterResult) GetPayMaster() string {
	if x != nil {
		return x.PayMaster
	}
	return ""
}

// AccessTuple is the element type of an access list.
type AspAccessTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address is a hex formatted ethereum address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// storage_keys are hex formatted hashes of the storage keys
	StorageKeys []string `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
}

func (x *AspAccessTuple) Reset() {
	*x = AspAccessTuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspAccessTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspAccessTuple) ProtoMessage() {}

func (x *AspAccessTuple) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspAccessTuple.ProtoReflect.Descriptor instead.
func (*AspAccessTuple) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{5}
}

func (x *AspAccessTuple) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AspAccessTuple) GetStorageKeys() []string {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

type AspTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// chain_id of the destination EVM chain
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// nonce corresponds to the account nonce (transaction sequence).
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// gas_tip_cap defines the max value for the gas tip
	GasTipCap string `protobuf:"bytes,3,opt,name=gas_tip_cap,json=gasTipCap,proto3" json:"gas_tip_cap,omitempty"`
	// gas_fee_cap defines the max value for the gas fee
	GasFeeCap string `protobuf:"bytes,4,opt,name=gas_fee_cap,json=gasFeeCap,proto3" json:"gas_fee_cap,omitempty"`
	// gas defines the gas limit defined for the transaction.
	GasLimit uint64 `protobuf:"varint,5,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice uint64 `protobuf:"varint,6,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// to is the hex formatted address of the recipient
	To string `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	// value defines the the transaction amount.
	Value uint64 `protobuf:"varint,8,opt,name=value,proto3" json:"value,omitempty"`
	// data is the data payload bytes of the transaction.
	Input []byte `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	// accesses is an array of access tuples
	AccessList       []*AspAccessTuple `protobuf:"bytes,10,rep,name=accessList,proto3" json:"accessList,omitempty"`
	BlockHash        []byte            `protobuf:"bytes,11,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber      int64             `protobuf:"varint,12,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	From             string            `protobuf:"bytes,13,opt,name=from,proto3" json:"from,omitempty"`
	Hash             []byte            `protobuf:"bytes,14,opt,name=hash,proto3" json:"hash,omitempty"`
	TransactionIndex int64             `protobuf:"varint,15,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	Type             uint64            `protobuf:"varint,16,opt,name=type,proto3" json:"type,omitempty"`
	// v defines the signature value
	V []byte `protobuf:"bytes,17,opt,name=v,proto3" json:"v,omitempty"`
	// r defines the signature value
	R []byte `protobuf:"bytes,18,opt,name=r,proto3" json:"r,omitempty"`
	// s define the signature value
	S []byte `protobuf:"bytes,19,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *AspTransaction) Reset() {
	*x = AspTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspTransaction) ProtoMessage() {}

func (x *AspTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspTransaction.ProtoReflect.Descriptor instead.
func (*AspTransaction) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{6}
}

func (x *AspTransaction) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *AspTransaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *AspTransaction) GetGasTipCap() string {
	if x != nil {
		return x.GasTipCap
	}
	return ""
}

func (x *AspTransaction) GetGasFeeCap() string {
	if x != nil {
		return x.GasFeeCap
	}
	return ""
}

func (x *AspTransaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *AspTransaction) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *AspTransaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AspTransaction) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AspTransaction) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *AspTransaction) GetAccessList() []*AspAccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *AspTransaction) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *AspTransaction) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AspTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AspTransaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *AspTransaction) GetTransactionIndex() int64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *AspTransaction) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AspTransaction) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *AspTransaction) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *AspTransaction) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type InnerTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To    string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Gas   string `protobuf:"bytes,5,opt,name=gas,proto3" json:"gas,omitempty"`
	Index uint64 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *InnerTransaction) Reset() {
	*x = InnerTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerTransaction) ProtoMessage() {}

func (x *InnerTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerTransaction.ProtoReflect.Descriptor instead.
func (*InnerTransaction) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{7}
}

func (x *InnerTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *InnerTransaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InnerTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InnerTransaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *InnerTransaction) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *InnerTransaction) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type AspectCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AspectId string `protobuf:"bytes,1,opt,name=aspectId,proto3" json:"aspectId,omitempty"`
	Version  uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Priority uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Code     []byte `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AspectCode) Reset() {
	*x = AspectCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspectCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectCode) ProtoMessage() {}

func (x *AspectCode) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectCode.ProtoReflect.Descriptor instead.
func (*AspectCode) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{8}
}

func (x *AspectCode) GetAspectId() string {
	if x != nil {
		return x.AspectId
	}
	return ""
}

func (x *AspectCode) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AspectCode) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AspectCode) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type BlockOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res   *BlockOutput_Result `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Block *EthBlock           `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *BlockOutput) Reset() {
	*x = BlockOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOutput) ProtoMessage() {}

func (x *BlockOutput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOutput.ProtoReflect.Descriptor instead.
func (*BlockOutput) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{9}
}

func (x *BlockOutput) GetRes() *BlockOutput_Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *BlockOutput) GetBlock() *EthBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

// EthBlock for querying ethereum block from aspect
type EthBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *EthHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Uncles       []*EthHeader      `protobuf:"bytes,2,rep,name=uncles,proto3" json:"uncles,omitempty"`
	Transactions []*AspTransaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Hash         string            `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Size         uint64            `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	DataHash     []byte            `protobuf:"bytes,6,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
}

func (x *EthBlock) Reset() {
	*x = EthBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthBlock) ProtoMessage() {}

func (x *EthBlock) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthBlock.ProtoReflect.Descriptor instead.
func (*EthBlock) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{10}
}

func (x *EthBlock) GetHeader() *EthHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EthBlock) GetUncles() []*EthHeader {
	if x != nil {
		return x.Uncles
	}
	return nil
}

func (x *EthBlock) GetTransactions() []*AspTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *EthBlock) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EthBlock) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EthBlock) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

type EthHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentHash    string `protobuf:"bytes,1,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	UncleHash     string `protobuf:"bytes,2,opt,name=uncleHash,proto3" json:"uncleHash,omitempty"`
	Miner         string `protobuf:"bytes,3,opt,name=miner,proto3" json:"miner,omitempty"`
	StateRoot     string `protobuf:"bytes,4,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	TxHash        string `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	ReceiptHash   string `protobuf:"bytes,6,opt,name=receiptHash,proto3" json:"receiptHash,omitempty"`
	Difficulty    uint64 `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number        uint64 `protobuf:"varint,8,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit      uint64 `protobuf:"varint,9,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed       uint64 `protobuf:"varint,10,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Timestamp     uint64 `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte `protobuf:"bytes,12,opt,name=extraData,proto3" json:"extraData,omitempty"`
	MixHash       []byte `protobuf:"bytes,13,opt,name=mixHash,proto3" json:"mixHash,omitempty"`
	Nonce         uint64 `protobuf:"varint,14,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BaseFeePerGas uint64 `protobuf:"varint,15,opt,name=baseFeePerGas,proto3" json:"baseFeePerGas,omitempty"`
}

func (x *EthHeader) Reset() {
	*x = EthHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthHeader) ProtoMessage() {}

func (x *EthHeader) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthHeader.ProtoReflect.Descriptor instead.
func (*EthHeader) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{11}
}

func (x *EthHeader) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *EthHeader) GetUncleHash() string {
	if x != nil {
		return x.UncleHash
	}
	return ""
}

func (x *EthHeader) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

func (x *EthHeader) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *EthHeader) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EthHeader) GetReceiptHash() string {
	if x != nil {
		return x.ReceiptHash
	}
	return ""
}

func (x *EthHeader) GetDifficulty() uint64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *EthHeader) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *EthHeader) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *EthHeader) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *EthHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EthHeader) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *EthHeader) GetMixHash() []byte {
	if x != nil {
		return x.MixHash
	}
	return nil
}

func (x *EthHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *EthHeader) GetBaseFeePerGas() uint64 {
	if x != nil {
		return x.BaseFeePerGas
	}
	return 0
}

type StateChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // hex string of account
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StateChange) Reset() {
	*x = StateChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChange) ProtoMessage() {}

func (x *StateChange) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChange.ProtoReflect.Descriptor instead.
func (*StateChange) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{12}
}

func (x *StateChange) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *StateChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StateChanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All []*StateChange `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *StateChanges) Reset() {
	*x = StateChanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChanges) ProtoMessage() {}

func (x *StateChanges) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChanges.ProtoReflect.Descriptor instead.
func (*StateChanges) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{13}
}

func (x *StateChanges) GetAll() []*StateChange {
	if x != nil {
		return x.All
	}
	return nil
}

type AspCallStacks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calls map[string]*InnerTransaction `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AspCallStacks) Reset() {
	*x = AspCallStacks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspCallStacks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspCallStacks) ProtoMessage() {}

func (x *AspCallStacks) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspCallStacks.ProtoReflect.Descriptor instead.
func (*AspCallStacks) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{14}
}

func (x *AspCallStacks) GetCalls() map[string]*InnerTransaction {
	if x != nil {
		return x.Calls
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind ValueKind `protobuf:"varint,1,opt,name=kind,proto3,enum=aspect.v1.ValueKind" json:"kind,omitempty"`
	Data []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{15}
}

func (x *Value) GetKind() ValueKind {
	if x != nil {
		return x.Kind
	}
	return ValueKind_INT16
}

func (x *Value) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Values struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All []*Value `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *Values) Reset() {
	*x = Values{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{16}
}

func (x *Values) GetAll() []*Value {
	if x != nil {
		return x.All
	}
	return nil
}

type AspLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address of the contract that generated the event
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// topics is a list of topics provided by the contract.
	Topics []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	// data which is supplied by the contract, usually ABI-encoded
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// block_number of the block in which the transaction was included
	BlockNumber uint64 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// tx_hash is the transaction hash
	TxHash string `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// tx_index of the transaction in the block
	TxIndex uint64 `protobuf:"varint,6,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	// block_hash of the block in which the transaction was included
	BlockHash string `protobuf:"bytes,7,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// index of the log in the block
	Index uint64 `protobuf:"varint,8,opt,name=index,proto3" json:"index,omitempty"`
	// removed is true if this log was reverted due to a chain
	// reorganisation. You must pay attention to this field if you receive logs
	// through a filter query.
	Removed bool `protobuf:"varint,9,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *AspLog) Reset() {
	*x = AspLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspLog) ProtoMessage() {}

func (x *AspLog) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspLog.ProtoReflect.Descriptor instead.
func (*AspLog) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{17}
}

func (x *AspLog) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AspLog) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *AspLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AspLog) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AspLog) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AspLog) GetTxIndex() uint64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *AspLog) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *AspLog) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AspLog) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// MsgEthereumTxResponse defines the Msg/EthereumTx response type.
type AspTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hash of the ethereum transaction in hex format. This hash differs from the
	// Tendermint sha256 hash of the transaction bytes. See
	// https://github.com/tendermint/tendermint/issues/6539 for reference
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// logs contains the transaction hash and the proto-compatible ethereum
	// logs.
	Logs []*AspLog `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	// ret is the returned data from evm function (result or data supplied with revert
	// opcode)
	Ret []byte `protobuf:"bytes,3,opt,name=ret,proto3" json:"ret,omitempty"`
	// vm_error is the error returned by vm execution
	VmError string `protobuf:"bytes,4,opt,name=vm_error,json=vmError,proto3" json:"vm_error,omitempty"`
	// gas_used specifies how much gas was consumed by the transaction
	GasUsed uint64 `protobuf:"varint,5,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
}

func (x *AspTxResponse) Reset() {
	*x = AspTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspTxResponse) ProtoMessage() {}

func (x *AspTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspTxResponse.ProtoReflect.Descriptor instead.
func (*AspTxResponse) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{18}
}

func (x *AspTxResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AspTxResponse) GetLogs() []*AspLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AspTxResponse) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *AspTxResponse) GetVmError() string {
	if x != nil {
		return x.VmError
	}
	return ""
}

func (x *AspTxResponse) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

// Validator
type AspValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // The first 20 bytes of SHA256(public key)
	// PubKey pub_key = 2 [(gogoproto.nullable)=false];
	Power int64 `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"` // The voting power
}

func (x *AspValidator) Reset() {
	*x = AspValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspValidator) ProtoMessage() {}

func (x *AspValidator) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspValidator.ProtoReflect.Descriptor instead.
func (*AspValidator) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{19}
}

func (x *AspValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AspValidator) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

// VoteInfo
type AspVoteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validator       *AspValidator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	SignedLastBlock bool          `protobuf:"varint,2,opt,name=signed_last_block,json=signedLastBlock,proto3" json:"signed_last_block,omitempty"`
}

func (x *AspVoteInfo) Reset() {
	*x = AspVoteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspVoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspVoteInfo) ProtoMessage() {}

func (x *AspVoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspVoteInfo.ProtoReflect.Descriptor instead.
func (*AspVoteInfo) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{20}
}

func (x *AspVoteInfo) GetValidator() *AspValidator {
	if x != nil {
		return x.Validator
	}
	return nil
}

func (x *AspVoteInfo) GetSignedLastBlock() bool {
	if x != nil {
		return x.SignedLastBlock
	}
	return false
}

type AspReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Consensus fields: These fields are defined by the Yellow Paper
	Type              uint32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	PostState         []byte    `protobuf:"bytes,2,opt,name=postState,proto3" json:"postState,omitempty"`
	Status            uint64    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CumulativeGasUsed uint64    `protobuf:"varint,4,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	LogsBloom         []byte    `protobuf:"bytes,5,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	Logs              []*AspLog `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	// Implementation fields: These fields are added by geth when processing a transaction.
	// They are stored in the chain database.
	TxHash          string `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	ContractAddress string `protobuf:"bytes,8,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	GasUsed         uint64 `protobuf:"varint,9,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	// Inclusion information: These fields provide information about the inclusion of the
	// transaction corresponding to this receipt.
	BlockHash        string `protobuf:"bytes,10,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber      string `protobuf:"bytes,11,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TransactionIndex uint32 `protobuf:"varint,12,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
}

func (x *AspReceipt) Reset() {
	*x = AspReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspReceipt) ProtoMessage() {}

func (x *AspReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspReceipt.ProtoReflect.Descriptor instead.
func (*AspReceipt) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{21}
}

func (x *AspReceipt) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AspReceipt) GetPostState() []byte {
	if x != nil {
		return x.PostState
	}
	return nil
}

func (x *AspReceipt) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AspReceipt) GetCumulativeGasUsed() uint64 {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return 0
}

func (x *AspReceipt) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *AspReceipt) GetLogs() []*AspLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AspReceipt) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AspReceipt) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *AspReceipt) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *AspReceipt) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *AspReceipt) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *AspReceipt) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

type BlockOutput_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BlockOutput_Result) Reset() {
	*x = BlockOutput_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v1_hostapi_message_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockOutput_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOutput_Result) ProtoMessage() {}

func (x *BlockOutput_Result) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v1_hostapi_message_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOutput_Result.ProtoReflect.Descriptor instead.
func (*BlockOutput_Result) Descriptor() ([]byte, []int) {
	return file_aspect_v1_hostapi_message_proto_rawDescGZIP(), []int{9, 0}
}

func (x *BlockOutput_Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockOutput_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_aspect_v1_hostapi_message_proto protoreflect.FileDescriptor

var file_aspect_v1_hostapi_message_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x41, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x29, 0x0a, 0x02, 0x74, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x73, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x02, 0x74, 0x78, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x54, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x54, 0x78, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x2c, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x78, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x22, 0x30, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x22, 0x32, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x0e, 0x41, 0x73, 0x70, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x84, 0x04, 0x0a, 0x0e, 0x41, 0x73, 0x70, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x67, 0x61, 0x73,
	0x5f, 0x74, 0x69, 0x70, 0x5f, 0x63, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x61, 0x73, 0x54, 0x69, 0x70, 0x43, 0x61, 0x70, 0x12, 0x1e, 0x0a, 0x0b, 0x67, 0x61, 0x73,
	0x5f, 0x66, 0x65, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x61, 0x73, 0x46, 0x65, 0x65, 0x43, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x73,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x61,
	0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x73, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x0a,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x76,
	0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x72, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x22, 0x88, 0x01, 0x0a,
	0x10, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x61,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x72, 0x0a, 0x0a, 0x41, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x0b,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x2f, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x38, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0xe9, 0x01, 0x0a, 0x08, 0x45, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2c,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x74, 0x68, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x06,
	0x75, 0x6e, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x74, 0x68, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x75, 0x6e, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x70,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x22, 0xb7, 0x03,
	0x0a, 0x09, 0x45, 0x74, 0x68, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x75,
	0x6e, 0x63, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x6e, 0x63, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69,
	0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x64, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67,
	0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x61,
	0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x47,
	0x61, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x46, 0x65,
	0x65, 0x50, 0x65, 0x72, 0x47, 0x61, 0x73, 0x22, 0x3d, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x41, 0x73, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x63,
	0x6b, 0x73, 0x12, 0x39, 0x0a, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73,
	0x70, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x1a, 0x55, 0x0a,
	0x0a, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x45, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x22, 0xf4, 0x01, 0x0a, 0x06, 0x41, 0x73,
	0x70, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64,
	0x22, 0x92, 0x01, 0x0a, 0x0d, 0x41, 0x73, 0x70, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x76, 0x6d, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61,
	0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x61,
	0x73, 0x55, 0x73, 0x65, 0x64, 0x22, 0x3e, 0x0a, 0x0c, 0x41, 0x73, 0x70, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x70, 0x0a, 0x0b, 0x41, 0x73, 0x70, 0x56, 0x6f, 0x74, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x70, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x4c, 0x61,
	0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x91, 0x03, 0x0a, 0x0a, 0x41, 0x73, 0x70, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x11, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61,
	0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x63, 0x75, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x12, 0x25, 0x0a, 0x04,
	0x6c, 0x6f, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c,
	0x6f, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a,
	0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x2a, 0x7f, 0x0a, 0x09, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x31,
	0x36, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x54,
	0x32, 0x35, 0x36, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x31, 0x36, 0x10,
	0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x05, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x49, 0x4e,
	0x54, 0x32, 0x35, 0x36, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x08,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x09, 0x42, 0x94, 0x01, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x13,
	0x48, 0x6f, 0x73, 0x74, 0x61, 0x70, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x61, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x61, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x09, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x15, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aspect_v1_hostapi_message_proto_rawDescOnce sync.Once
	file_aspect_v1_hostapi_message_proto_rawDescData = file_aspect_v1_hostapi_message_proto_rawDesc
)

func file_aspect_v1_hostapi_message_proto_rawDescGZIP() []byte {
	file_aspect_v1_hostapi_message_proto_rawDescOnce.Do(func() {
		file_aspect_v1_hostapi_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspect_v1_hostapi_message_proto_rawDescData)
	})
	return file_aspect_v1_hostapi_message_proto_rawDescData
}

var file_aspect_v1_hostapi_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aspect_v1_hostapi_message_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_aspect_v1_hostapi_message_proto_goTypes = []interface{}{
	(ValueKind)(0),             // 0: aspect.v1.ValueKind
	(*AspectInput)(nil),        // 1: aspect.v1.AspectInput
	(*AspectOutput)(nil),       // 2: aspect.v1.AspectOutput
	(*FilterTxResult)(nil),     // 3: aspect.v1.FilterTxResult
	(*VerifyTxResult)(nil),     // 4: aspect.v1.VerifyTxResult
	(*GetPayMasterResult)(nil), // 5: aspect.v1.GetPayMasterResult
	(*AspAccessTuple)(nil),     // 6: aspect.v1.AspAccessTuple
	(*AspTransaction)(nil),     // 7: aspect.v1.AspTransaction
	(*InnerTransaction)(nil),   // 8: aspect.v1.InnerTransaction
	(*AspectCode)(nil),         // 9: aspect.v1.AspectCode
	(*BlockOutput)(nil),        // 10: aspect.v1.BlockOutput
	(*EthBlock)(nil),           // 11: aspect.v1.EthBlock
	(*EthHeader)(nil),          // 12: aspect.v1.EthHeader
	(*StateChange)(nil),        // 13: aspect.v1.StateChange
	(*StateChanges)(nil),       // 14: aspect.v1.StateChanges
	(*AspCallStacks)(nil),      // 15: aspect.v1.AspCallStacks
	(*Value)(nil),              // 16: aspect.v1.Value
	(*Values)(nil),             // 17: aspect.v1.Values
	(*AspLog)(nil),             // 18: aspect.v1.AspLog
	(*AspTxResponse)(nil),      // 19: aspect.v1.AspTxResponse
	(*AspValidator)(nil),       // 20: aspect.v1.AspValidator
	(*AspVoteInfo)(nil),        // 21: aspect.v1.AspVoteInfo
	(*AspReceipt)(nil),         // 22: aspect.v1.AspReceipt
	(*BlockOutput_Result)(nil), // 23: aspect.v1.BlockOutput.Result
	nil,                        // 24: aspect.v1.AspCallStacks.CallsEntry
	(*anypb.Any)(nil),          // 25: google.protobuf.Any
}
var file_aspect_v1_hostapi_message_proto_depIdxs = []int32{
	7,  // 0: aspect.v1.AspectInput.tx:type_name -> aspect.v1.AspTransaction
	8,  // 1: aspect.v1.AspectInput.currInnerTx:type_name -> aspect.v1.InnerTransaction
	25, // 2: aspect.v1.AspectOutput.resultData:type_name -> google.protobuf.Any
	6,  // 3: aspect.v1.AspTransaction.accessList:type_name -> aspect.v1.AspAccessTuple
	23, // 4: aspect.v1.BlockOutput.res:type_name -> aspect.v1.BlockOutput.Result
	11, // 5: aspect.v1.BlockOutput.block:type_name -> aspect.v1.EthBlock
	12, // 6: aspect.v1.EthBlock.header:type_name -> aspect.v1.EthHeader
	12, // 7: aspect.v1.EthBlock.uncles:type_name -> aspect.v1.EthHeader
	7,  // 8: aspect.v1.EthBlock.transactions:type_name -> aspect.v1.AspTransaction
	13, // 9: aspect.v1.StateChanges.all:type_name -> aspect.v1.StateChange
	24, // 10: aspect.v1.AspCallStacks.calls:type_name -> aspect.v1.AspCallStacks.CallsEntry
	0,  // 11: aspect.v1.Value.kind:type_name -> aspect.v1.ValueKind
	16, // 12: aspect.v1.Values.all:type_name -> aspect.v1.Value
	18, // 13: aspect.v1.AspTxResponse.logs:type_name -> aspect.v1.AspLog
	20, // 14: aspect.v1.AspVoteInfo.validator:type_name -> aspect.v1.AspValidator
	18, // 15: aspect.v1.AspReceipt.logs:type_name -> aspect.v1.AspLog
	8,  // 16: aspect.v1.AspCallStacks.CallsEntry.value:type_name -> aspect.v1.InnerTransaction
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_aspect_v1_hostapi_message_proto_init() }
func file_aspect_v1_hostapi_message_proto_init() {
	if File_aspect_v1_hostapi_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aspect_v1_hostapi_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspectInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspectOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterTxResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTxResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayMasterResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspAccessTuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspectCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspCallStacks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Values); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspVoteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v1_hostapi_message_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockOutput_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_aspect_v1_hostapi_message_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspect_v1_hostapi_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aspect_v1_hostapi_message_proto_goTypes,
		DependencyIndexes: file_aspect_v1_hostapi_message_proto_depIdxs,
		EnumInfos:         file_aspect_v1_hostapi_message_proto_enumTypes,
		MessageInfos:      file_aspect_v1_hostapi_message_proto_msgTypes,
	}.Build()
	File_aspect_v1_hostapi_message_proto = out.File
	file_aspect_v1_hostapi_message_proto_rawDesc = nil
	file_aspect_v1_hostapi_message_proto_goTypes = nil
	file_aspect_v1_hostapi_message_proto_depIdxs = nil
}
