// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: aspect/v2/joinpoint_input.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoFromTxInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	To   []byte `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
}

func (x *NoFromTxInput) Reset() {
	*x = NoFromTxInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoFromTxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoFromTxInput) ProtoMessage() {}

func (x *NoFromTxInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoFromTxInput.ProtoReflect.Descriptor instead.
func (*NoFromTxInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{0}
}

func (x *NoFromTxInput) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *NoFromTxInput) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

type WithFromTxInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	To   []byte `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
	From []byte `protobuf:"bytes,3,req,name=from" json:"from,omitempty"`
}

func (x *WithFromTxInput) Reset() {
	*x = WithFromTxInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithFromTxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithFromTxInput) ProtoMessage() {}

func (x *WithFromTxInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithFromTxInput.ProtoReflect.Descriptor instead.
func (*WithFromTxInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{1}
}

func (x *WithFromTxInput) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *WithFromTxInput) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *WithFromTxInput) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

type PreExecMessageInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  []byte  `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To    []byte  `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
	Index *uint64 `protobuf:"varint,3,req,name=index" json:"index,omitempty"`
	Data  []byte  `protobuf:"bytes,4,req,name=data" json:"data,omitempty"`
	Value []byte  `protobuf:"bytes,5,req,name=value" json:"value,omitempty"`
	Gas   *uint64 `protobuf:"varint,6,req,name=gas" json:"gas,omitempty"`
}

func (x *PreExecMessageInput) Reset() {
	*x = PreExecMessageInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreExecMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreExecMessageInput) ProtoMessage() {}

func (x *PreExecMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreExecMessageInput.ProtoReflect.Descriptor instead.
func (*PreExecMessageInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{2}
}

func (x *PreExecMessageInput) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PreExecMessageInput) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *PreExecMessageInput) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *PreExecMessageInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PreExecMessageInput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PreExecMessageInput) GetGas() uint64 {
	if x != nil && x.Gas != nil {
		return *x.Gas
	}
	return 0
}

type PostExecMessageInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  []byte  `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To    []byte  `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
	Index *uint64 `protobuf:"varint,3,req,name=index" json:"index,omitempty"`
	Data  []byte  `protobuf:"bytes,4,req,name=data" json:"data,omitempty"`
	Value []byte  `protobuf:"bytes,5,req,name=value" json:"value,omitempty"`
	Gas   *uint64 `protobuf:"varint,6,opt,name=gas" json:"gas,omitempty"`
	Ret   []byte  `protobuf:"bytes,7,opt,name=ret" json:"ret,omitempty"`
	Error *string `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
}

func (x *PostExecMessageInput) Reset() {
	*x = PostExecMessageInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostExecMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostExecMessageInput) ProtoMessage() {}

func (x *PostExecMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostExecMessageInput.ProtoReflect.Descriptor instead.
func (*PostExecMessageInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{3}
}

func (x *PostExecMessageInput) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PostExecMessageInput) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *PostExecMessageInput) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *PostExecMessageInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PostExecMessageInput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PostExecMessageInput) GetGas() uint64 {
	if x != nil && x.Gas != nil {
		return *x.Gas
	}
	return 0
}

func (x *PostExecMessageInput) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *PostExecMessageInput) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type BlockInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number *uint64 `protobuf:"varint,1,req,name=number" json:"number,omitempty"`
}

func (x *BlockInput) Reset() {
	*x = BlockInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInput) ProtoMessage() {}

func (x *BlockInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInput.ProtoReflect.Descriptor instead.
func (*BlockInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{4}
}

func (x *BlockInput) GetNumber() uint64 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

type ReceiptInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *uint64 `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
}

func (x *ReceiptInput) Reset() {
	*x = ReceiptInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptInput) ProtoMessage() {}

func (x *ReceiptInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptInput.ProtoReflect.Descriptor instead.
func (*ReceiptInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiptInput) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type TxVerifyInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx             *NoFromTxInput `protobuf:"bytes,1,req,name=tx" json:"tx,omitempty"`
	Block          *BlockInput    `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
	ValidationData []byte         `protobuf:"bytes,3,req,name=validation_data,json=validationData" json:"validation_data,omitempty"`
	CallData       []byte         `protobuf:"bytes,4,req,name=call_data,json=callData" json:"call_data,omitempty"`
}

func (x *TxVerifyInput) Reset() {
	*x = TxVerifyInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxVerifyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxVerifyInput) ProtoMessage() {}

func (x *TxVerifyInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxVerifyInput.ProtoReflect.Descriptor instead.
func (*TxVerifyInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{6}
}

func (x *TxVerifyInput) GetTx() *NoFromTxInput {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *TxVerifyInput) GetBlock() *BlockInput {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *TxVerifyInput) GetValidationData() []byte {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

func (x *TxVerifyInput) GetCallData() []byte {
	if x != nil {
		return x.CallData
	}
	return nil
}

type PreTxExecuteInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx    *WithFromTxInput `protobuf:"bytes,1,req,name=tx" json:"tx,omitempty"`
	Block *BlockInput      `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
}

func (x *PreTxExecuteInput) Reset() {
	*x = PreTxExecuteInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreTxExecuteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreTxExecuteInput) ProtoMessage() {}

func (x *PreTxExecuteInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreTxExecuteInput.ProtoReflect.Descriptor instead.
func (*PreTxExecuteInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{7}
}

func (x *PreTxExecuteInput) GetTx() *WithFromTxInput {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *PreTxExecuteInput) GetBlock() *BlockInput {
	if x != nil {
		return x.Block
	}
	return nil
}

type OperationInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx       *WithFromTxInput `protobuf:"bytes,1,req,name=tx" json:"tx,omitempty"`
	Block    *BlockInput      `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
	CallData []byte           `protobuf:"bytes,3,req,name=call_data,json=callData" json:"call_data,omitempty"`
}

func (x *OperationInput) Reset() {
	*x = OperationInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationInput) ProtoMessage() {}

func (x *OperationInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationInput.ProtoReflect.Descriptor instead.
func (*OperationInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{8}
}

func (x *OperationInput) GetTx() *WithFromTxInput {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *OperationInput) GetBlock() *BlockInput {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *OperationInput) GetCallData() []byte {
	if x != nil {
		return x.CallData
	}
	return nil
}

type PostTxExecuteInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx      *WithFromTxInput `protobuf:"bytes,1,req,name=tx" json:"tx,omitempty"`
	Block   *BlockInput      `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
	Receipt *ReceiptInput    `protobuf:"bytes,3,req,name=receipt" json:"receipt,omitempty"`
}

func (x *PostTxExecuteInput) Reset() {
	*x = PostTxExecuteInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTxExecuteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTxExecuteInput) ProtoMessage() {}

func (x *PostTxExecuteInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTxExecuteInput.ProtoReflect.Descriptor instead.
func (*PostTxExecuteInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{9}
}

func (x *PostTxExecuteInput) GetTx() *WithFromTxInput {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *PostTxExecuteInput) GetBlock() *BlockInput {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *PostTxExecuteInput) GetReceipt() *ReceiptInput {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type PreContractCallInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Call  *PreExecMessageInput `protobuf:"bytes,1,req,name=call" json:"call,omitempty"`
	Block *BlockInput          `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
}

func (x *PreContractCallInput) Reset() {
	*x = PreContractCallInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreContractCallInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreContractCallInput) ProtoMessage() {}

func (x *PreContractCallInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreContractCallInput.ProtoReflect.Descriptor instead.
func (*PreContractCallInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{10}
}

func (x *PreContractCallInput) GetCall() *PreExecMessageInput {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *PreContractCallInput) GetBlock() *BlockInput {
	if x != nil {
		return x.Block
	}
	return nil
}

type PostContractCallInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Call  *PostExecMessageInput `protobuf:"bytes,1,req,name=call" json:"call,omitempty"`
	Block *BlockInput           `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
}

func (x *PostContractCallInput) Reset() {
	*x = PostContractCallInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostContractCallInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostContractCallInput) ProtoMessage() {}

func (x *PostContractCallInput) ProtoReflect() protoreflect.Message {
	mi := &file_aspect_v2_joinpoint_input_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostContractCallInput.ProtoReflect.Descriptor instead.
func (*PostContractCallInput) Descriptor() ([]byte, []int) {
	return file_aspect_v2_joinpoint_input_proto_rawDescGZIP(), []int{11}
}

func (x *PostContractCallInput) GetCall() *PostExecMessageInput {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *PostContractCallInput) GetBlock() *BlockInput {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_aspect_v2_joinpoint_input_proto protoreflect.FileDescriptor

var file_aspect_v2_joinpoint_input_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x6a, 0x6f, 0x69, 0x6e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x22, 0x33, 0x0a, 0x0d,
	0x4e, 0x6f, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02, 0x74,
	0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x57, 0x69, 0x74, 0x68, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x78, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x8b, 0x01, 0x0a,
	0x13, 0x50, 0x72, 0x65, 0x45, 0x78, 0x65, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18,
	0x06, 0x20, 0x02, 0x28, 0x04, 0x52, 0x03, 0x67, 0x61, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x14, 0x50,
	0x6f, 0x73, 0x74, 0x45, 0x78, 0x65, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x61, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x24, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0xac, 0x01, 0x0a, 0x0d, 0x54, 0x78, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x28, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x6f, 0x46, 0x72, 0x6f, 0x6d,
	0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x02, 0x74, 0x78, 0x12, 0x2b, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6c,
	0x0a, 0x11, 0x50, 0x72, 0x65, 0x54, 0x78, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x74, 0x68,
	0x46, 0x72, 0x6f, 0x6d, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x02, 0x74, 0x78, 0x12,
	0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x86, 0x01, 0x0a,
	0x0e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x46, 0x72, 0x6f, 0x6d,
	0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x02, 0x74, 0x78, 0x12, 0x2b, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x61, 0x6c,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x78,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x78, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x02, 0x74, 0x78, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x2e, 0x76, 0x32, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e,
	0x76, 0x32, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x77, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x32, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72, 0x65, 0x45, 0x78,
	0x65, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x04,
	0x63, 0x61, 0x6c, 0x6c, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x22, 0x79, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x63, 0x61,
	0x6c, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x78, 0x65, 0x63, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x12,
	0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x96, 0x01, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x32, 0x42, 0x13,
	0x4a, 0x6f, 0x69, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x61, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x61, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x41, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x2e, 0x56, 0x32, 0xca, 0x02, 0x09, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5c, 0x56, 0x32,
	0xe2, 0x02, 0x15, 0x41, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x41, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x3a, 0x3a, 0x56, 0x32,
}

var (
	file_aspect_v2_joinpoint_input_proto_rawDescOnce sync.Once
	file_aspect_v2_joinpoint_input_proto_rawDescData = file_aspect_v2_joinpoint_input_proto_rawDesc
)

func file_aspect_v2_joinpoint_input_proto_rawDescGZIP() []byte {
	file_aspect_v2_joinpoint_input_proto_rawDescOnce.Do(func() {
		file_aspect_v2_joinpoint_input_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspect_v2_joinpoint_input_proto_rawDescData)
	})
	return file_aspect_v2_joinpoint_input_proto_rawDescData
}

var file_aspect_v2_joinpoint_input_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_aspect_v2_joinpoint_input_proto_goTypes = []interface{}{
	(*NoFromTxInput)(nil),         // 0: aspect.v2.NoFromTxInput
	(*WithFromTxInput)(nil),       // 1: aspect.v2.WithFromTxInput
	(*PreExecMessageInput)(nil),   // 2: aspect.v2.PreExecMessageInput
	(*PostExecMessageInput)(nil),  // 3: aspect.v2.PostExecMessageInput
	(*BlockInput)(nil),            // 4: aspect.v2.BlockInput
	(*ReceiptInput)(nil),          // 5: aspect.v2.ReceiptInput
	(*TxVerifyInput)(nil),         // 6: aspect.v2.TxVerifyInput
	(*PreTxExecuteInput)(nil),     // 7: aspect.v2.PreTxExecuteInput
	(*OperationInput)(nil),        // 8: aspect.v2.OperationInput
	(*PostTxExecuteInput)(nil),    // 9: aspect.v2.PostTxExecuteInput
	(*PreContractCallInput)(nil),  // 10: aspect.v2.PreContractCallInput
	(*PostContractCallInput)(nil), // 11: aspect.v2.PostContractCallInput
}
var file_aspect_v2_joinpoint_input_proto_depIdxs = []int32{
	0,  // 0: aspect.v2.TxVerifyInput.tx:type_name -> aspect.v2.NoFromTxInput
	4,  // 1: aspect.v2.TxVerifyInput.block:type_name -> aspect.v2.BlockInput
	1,  // 2: aspect.v2.PreTxExecuteInput.tx:type_name -> aspect.v2.WithFromTxInput
	4,  // 3: aspect.v2.PreTxExecuteInput.block:type_name -> aspect.v2.BlockInput
	1,  // 4: aspect.v2.OperationInput.tx:type_name -> aspect.v2.WithFromTxInput
	4,  // 5: aspect.v2.OperationInput.block:type_name -> aspect.v2.BlockInput
	1,  // 6: aspect.v2.PostTxExecuteInput.tx:type_name -> aspect.v2.WithFromTxInput
	4,  // 7: aspect.v2.PostTxExecuteInput.block:type_name -> aspect.v2.BlockInput
	5,  // 8: aspect.v2.PostTxExecuteInput.receipt:type_name -> aspect.v2.ReceiptInput
	2,  // 9: aspect.v2.PreContractCallInput.call:type_name -> aspect.v2.PreExecMessageInput
	4,  // 10: aspect.v2.PreContractCallInput.block:type_name -> aspect.v2.BlockInput
	3,  // 11: aspect.v2.PostContractCallInput.call:type_name -> aspect.v2.PostExecMessageInput
	4,  // 12: aspect.v2.PostContractCallInput.block:type_name -> aspect.v2.BlockInput
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_aspect_v2_joinpoint_input_proto_init() }
func file_aspect_v2_joinpoint_input_proto_init() {
	if File_aspect_v2_joinpoint_input_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aspect_v2_joinpoint_input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoFromTxInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithFromTxInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreExecMessageInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostExecMessageInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxVerifyInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreTxExecuteInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostTxExecuteInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreContractCallInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspect_v2_joinpoint_input_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostContractCallInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspect_v2_joinpoint_input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aspect_v2_joinpoint_input_proto_goTypes,
		DependencyIndexes: file_aspect_v2_joinpoint_input_proto_depIdxs,
		MessageInfos:      file_aspect_v2_joinpoint_input_proto_msgTypes,
	}.Build()
	File_aspect_v2_joinpoint_input_proto = out.File
	file_aspect_v2_joinpoint_input_proto_rawDesc = nil
	file_aspect_v2_joinpoint_input_proto_goTypes = nil
	file_aspect_v2_joinpoint_input_proto_depIdxs = nil
}
