package context

var PreCallCtxKeys = []interface{}{
	BlockHeaderParentHash,
	BlockHeaderMiner,
	BlockHeaderTransactionsRoot,
	BlockHeaderNumber,
	BlockHeaderGasLimit,
	BlockHeaderGasUsed,
	BlockHeaderTimestamp,
	BlockHeaderBaseFee,
	BlockTxsSize,

	EnvExtraEIPs,
	EnvEnableCreate,
	EnvEnableCall,
	EnvAllowUnprotectedTxs,
	EnvChainChainId,
	EnvChainHomesteadBlock,
	EnvChainDaoForkBlock,
	EnvChainDaoForkSupport,
	EnvChainEip150Block,
	EnvChainEip155Block,
	EnvChainEip158Block,
	EnvChainByzantiumBlock,
	EnvChainConstantinopleBlock,
	EnvChainPetersburgBlock,
	EnvChainIstanbulBlock,
	EnvChainMuirGlacierBlock,
	EnvChainBerlinBlock,
	EnvChainLondonBlock,
	EnvChainArrowGlacierBlock,
	EnvChainGrayGlacierBlock,
	EnvChainMergeNetSplitBlock,
	EnvChainShanghaiTime,
	EnvChainCancunTime,
	EnvChainPragueTime,
	EnvConsensusParamsBlockPeriod,
	EnvConsensusParamsMaxGasLimit,
	EnvConsensusParamsMaxExtraData,
	EnvConsensusParamsMaxUncleBlocks,
	EnvConsensusParamsMaxAgeDuration,
	EnvConsensusParamsMaxBytes,
	EnvConsensusParamsValidatorPubKeyTypes,
	EnvConsensusParamsVersion,

	TxType,
	TxChainId,
	TxAccessList,
	TxNonce,
	TxGasPrice,
	TxGas,
	TxGasTipCap,
	TxGasFeeCap,
	TxTo,
	TxValue,
	TxData,
	TxBytes,
	TxHash,
	TxUnsignedBytes,
	TxUnsignedHash,
	TxSigV,
	TxSigR,
	TxSigS,
	TxFrom,
	TxIndex,

	AspectId,
	AspectVersion,

	MsgFrom,
	MsgTo,
	MsgValue,
	MsgGas,
	MsgInput,
	MsgIndex,
}
