package context

var VerifyTxCtxKeys = []interface{}{
	BlockHeaderNumber,

	EnvExtraEIPs,
	EnvEnableCreate,
	EnvEnableCall,
	EnvAllowUnprotectedTxs,
	EnvChainChainId,
	EnvChainHomesteadBlock,
	EnvChainDaoForkBlock,
	EnvChainDaoForkSupport,
	EnvChainEip150Block,
	EnvChainEip155Block,
	EnvChainEip158Block,
	EnvChainByzantiumBlock,
	EnvChainConstantinopleBlock,
	EnvChainPetersburgBlock,
	EnvChainIstanbulBlock,
	EnvChainMuirGlacierBlock,
	EnvChainBerlinBlock,
	EnvChainLondonBlock,
	EnvChainArrowGlacierBlock,
	EnvChainGrayGlacierBlock,
	EnvChainMergeNetSplitBlock,
	EnvChainShanghaiTime,
	EnvChainCancunTime,
	EnvChainPragueTime,
	EnvConsensusParamsBlockPeriod,
	EnvConsensusParamsMaxGasLimit,
	EnvConsensusParamsMaxExtraData,
	EnvConsensusParamsMaxUncleBlocks,
	EnvConsensusParamsMaxAgeDuration,
	EnvConsensusParamsMaxBytes,
	EnvConsensusParamsValidatorPubKeyTypes,
	EnvConsensusParamsVersion,

	TxType,
	TxAccessList,
	TxNonce,
	TxGasPrice,
	TxGas,
	TxGasTipCap,
	TxGasFeeCap,
	TxTo,
	TxValue,
	TxData,
	TxUnsignedBytes,
	TxUnsignedHash,

	AspectId,
	AspectVersion,
}
